name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  workflow_dispatch:
jobs:
  deploy:
    # secrets:
    #   GCP_PROJECT_ID
    #   GCP_PROJECT_NUMBER
    #   GCP_REGION
    #   GCP_SERVICE
    if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |-
          # set IMAGE_TAG
          image_tag=$(echo '${{ github.ref_name }}')
          echo "IMAGE_TAG=${image_tag}" >> $GITHUB_ENV
          # set IMAGE_URL
          region=${{ secrets.GCP_REGION }}
          project_id="${{ secrets.GCP_PROJECT_ID }}"
          repository="${{ secrets.GCP_SERVICE }}"
          image_name="${{ secrets.GCP_SERVICE }}"
          image_url="${region}-docker.pkg.dev/${project_id}/${repository}/${image_name}:${image_tag}"
          echo "IMAGE_URL=${image_url}" >> $GITHUB_ENV
      # Deploy to GitHub Container Registry
      - uses: VaultVulp/gp-docker-action@1.5.0
        with:
          build-context: .
          dockerfile: Dockerfile
          # extract-git-tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: genuuid
          image-tag: ${{ env.IMAGE_TAG }}
      # Deploy to Google Cloud Artifact Registry & Cloud Run
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          service_account: "deploy-${{ secrets.GCP_SERVICE }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_SERVICE }}-pool/providers/${{ secrets.GCP_SERVICE }}-provider"
      - uses: google-github-actions/setup-gcloud@v1
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - run: |-
          docker build --tag ${IMAGE_URL} .
          docker push ${IMAGE_URL}
      - run: |-
          gcloud run deploy ${{ secrets.GCP_SERVICE }} \
            --allow-unauthenticated \
            --args "server" \
            --image ${IMAGE_URL} \
            --max-instances "1" \
            --memory "1024Mi" \
            --platform "managed" \
            --quiet \
            --region ${{ secrets.GCP_REGION }} \
            --service-account run-${{ secrets.GCP_SERVICE }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --set-env-vars "BASE_PATH=/lab/genuuid"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
